parameters:
- name: NMH
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        Yoruba: 
          epochs:
            1: start_size 
- name: TY 
  upper_bound: 300000
  values:
    - demes: 
        Yoruba: 
          epochs:
            1: end_time 
- name: NY
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        Yoruba: 
          epochs:
            2: start_size 