parameters:
- name: NA 
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        A: 
          epochs:
            0: start_size 
- name: TA
  lower_bound: 50000
  values:
    - demes: 
        A: 
          epochs:
            0: end_time
- name: TF
  lower_bound: 10000
  values:
    - demes: 
        French: 
          epochs:
            0: end_time
- name: NF
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        French: 
          epochs:
            1: start_size
- name: NY
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        Yoruba: 
          epochs:
            0: start_size 
- name: mFY
  lower_bound: 1e-8
  upper_bound: 1e-3
  values:
    - migrations:
        0: rate

constraints:
- params: [TA, TF]
  constraint: greater_than