parameters:
- name: TA
  upper_bound: 1000000
  values:
    - demes:
        Anc:
          epochs:
            0: end_time
- name: NND
  lower_bound: 10
  upper_bound: 40000
  values:
    - demes:
        ND:
          epochs:
            0: start_size
- name: TND
  values:
    - demes:
        ND:
          epochs:
            0: end_time

- name: TN
  values:
    - demes:
        N:
          epochs:
            0: end_time

- name: TCV
  values:
    - demes:
        CV:
          epochs:
            0: end_time

- name: TNI
  values:
    - demes:
        NI: start_time
# T NI -> OOA := 50000

- name: NMH
  lower_bound: 1
  upper_bound: 50000
  values:
    - demes:
        MH:
          epochs:
            0: start_size

- name: TMHI
  lower_bound: 121000
  values:
  - demes:
      MHI: start_time
# T MHI -> Altai := 120000

- name: TMH
  lower_bound: 61000
  values:
    - demes:
        MH:
          epochs:
            0: end_time
# TOOA := 60000

- name: THFP
  upper_bound: 49000
  values:
    - demes:
        MH:
          epochs:
            0: end_time

- name: THP
  lower_bound: 12000
  values:
    - demes:
        MH:
          epochs:
            0: end_time

constraints:
- params: [TA, TND]
  constraint: greater_than
- params: [TND, TN]
  constraint: greater_than
- params: [TN, TVC]
  constraint: greater_than
- params: [TCV, TNI]
  constraint: greater_than

- params: [TA, TMHI]
  constraint: greater_than
- params: [TMHI, TMH]
  constraint: greater_than

- params: [THFP, THP]
  constraint: greater_than