

reps = list(range(50))


rule all:
    input:
        expand('fit_{rep}.yaml', rep=reps)


rule fit:
    input:
        d = "../../../bootstrap.pkl",
        g = "tree.yaml",
        p = "params.yaml"
    output:
        "fit_{rep}.yaml"
    shell:
        """
        fit_H2 -u 1.112e-8 -d {input.d} -p {input.p} -g {input.g} \
            -o {output} --max_iter 100 --method Powell --perturb 1 --verbose 50
        """
