parameters:
- name: NA 
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        A: 
          epochs:
            0: start_size 
- name: NND
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        ND: 
          epochs:
            0: start_size
- name: TND
  upper_bound: 790000
  values:
    - demes: 
        ND: 
          epochs:
            0: end_time
- name: ND
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        Denisova: 
          epochs:
            0: start_size
- name: NV
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        Vindija: 
          epochs:
            0: start_size
- name: NY
  lower_bound: 100
  upper_bound: 100000
  values:
    - demes: 
        Yoruba: 
          epochs:
            0: start_size 
- name: pYV
  lower_bound: 0.01
  upper_bound: 0.15
  values:
    - pulses:
        0: 
          proportions: 0