log = out/job_$(Cluster)_$(Process).log
error = out/job_$(Cluster)_$(Process).err
output = out/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/archaic-container.sif

executable = H2_map_test.sh


arguments = --cluster_id $(Cluster) --process_id $(Process) \
            -u 1.35e-8 -r 1e-8 -n 100 -L 10e6 \
	    --max_iter 100 --opt_method Powell -v 10 --n_reps 100 --return_best 1 \ 
            -g IM_graph.yaml -p IM_params.yaml -o maptest


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = H2_map_test.py, IM_graph.yaml, IM_params.yaml


request_cpus = 1
request_memory = 4GB
request_disk = 1GB

queue 100
